server:
    servlet:
      context-path: /wakacop

spring:
  datasource:
    url: jdbc:h2:mem:demob
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console